// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:f79cb195-6279-429e-ae9c-022c07d23fe5",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_U8nETZDdB",
    "aws_user_pools_web_client_id": "3iri7bgocftd4qgh55n1f50ind",
    "oauth": {}
};


export default awsmobile;
