/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'eu-west-1',
  aws_cognito_identity_pool_id:
    'eu-west-1:06863165-5b56-4598-8e87-cc9ae2895f39',
  aws_cognito_region: 'eu-west-1',
  aws_user_pools_id: 'eu-west-1_sk5LfmU4g',
  aws_user_pools_web_client_id: '6d5of62ku9g4pcl2jpp0rcng67',
  oauth: {},
}

export default awsmobile
